repos:
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        entry: bash -c 'cargo check'
        language: system
        stages: [pre-commit]

      - id: cargo-test
        name: cargo test compile-only
        entry: bash -c 'cargo test'
        language: system
        stages: [pre-commit]