[package]
name = "frog"
version = "0.1.0"
edition = "2024"

[dependencies]
anstyle = "1.0.13"
clap = { version = "4.5.53", features = ["derive"] }
indicatif = "0.18.3"
nalgebra = "0.34.1"
rand = "0.9.2"
rand_chacha = "0.9.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
